include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Enforce good practices
    always_declare_return_types: true
    avoid_empty_else: true
    avoid_print: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_void: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    empty_catches: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_single_quotes: true
    sort_pub_dependencies: false
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_null_checks: true
    use_key_in_widget_constructors: true

analyzer:
  errors:
    missing_return: error
    dead_code: warning
    unused_import: warning
    unused_local_variable: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/injection.config.dart"
